import type { NextPage } from 'next'
import Head from 'next/head'
import { Chart } from '../components/chart'
import styles from '../styles/Home.module.css'
import { prices } from '../data'
import { useState } from 'react'

const Home: NextPage = () => {
  const [pair, setPair] = useState(prices[0].id)
  const tokenPrice = prices.find(x => x.id == pair)?.data ?? []
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Smart DCA simulation
        </h3>
        <div>
          <select onChange={(e) => setPair(e.target.value)} value={pair} >
            {prices.map(({ id, name }) => (
              <option key={id} value={id} >{name}</option>
            ))}
          </select>
        </div>

        <Chart tokenPrice={tokenPrice} classicDCAValues={[1, 2, 3, 4]} smartDCAValues={[4, 3, 2, 1]} />
      </main>

    </div>
  )
}

export default Home
